- setup.py
* Adds entry points for Invenio-Base to discover the extension.
> installation: entry points addition

- AUTHORS.rst
- example/app.py
- example/templates/settings/base.html
- example/templates/settings/item1.html
- example/templates/settings/item2.html
- invenio_theme/ext.py
- invenio_theme/templates/invenio_theme/page_cover.html
- invenio_theme/templates/invenio_theme/settings/base.html
- invenio_theme/templates/invenio_theme/settings/content.html
- invenio_theme/templates/invenio_theme/settings/menu.html
- run-tests.sh
- tests/test_invenio_theme.py
* NEW Adds a cover template which doesn't render page footer or header.
(closes #8)
Signed-off-by: Sami Hiltunen <sami.mikael.hiltunen@cern.ch>
> theme: addition of cover template

- .travis.yml
- AUTHORS.rst
- example/app.py
- example/templates/cover.html
- example/templates/settings/base.html
- example/templates/settings/item1.html
- example/templates/settings/item2.html
- invenio_theme/ext.py
- invenio_theme/templates/invenio_theme/page_cover.html
- invenio_theme/templates/invenio_theme/settings/base.html
- invenio_theme/templates/invenio_theme/settings/content.html
- invenio_theme/templates/invenio_theme/settings/menu.html
- invenio_theme/version.py
- requirements-devel.txt
- run-tests.sh
- setup.py
- tests/test_invenio_theme.py
Pending Flask-Menu 0.5.0 release and 2-3 PRs still to be integrated.
> Invenio-Theme v1.0.0a2

- .travis.yml
- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_theme/templates/invenio_theme/header_login.html
- invenio_theme/templates/invenio_theme/page_cover.html
- invenio_theme/templates/invenio_theme/settings/base.html
- invenio_theme/templates/invenio_theme/settings/content.html
- invenio_theme/version.py
- setup.py
- tests/test_invenio_theme.py
> templates: minor adjustments

- invenio_theme/ext.py
- invenio_theme/views.py
- setup.py
- tests/conftest.py
- tests/test_invenio_theme_error_handler.py
* Added custom error handlers to errors 401,
403 and 404. (Closes #13)
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>
> views: addition of custom error handlers 401, 403, 404

- invenio_theme/ext.py
- invenio_theme/static/js/build.js
> static: addition of build.js configuration

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_theme/version.py
> Invenio-Theme v1.0.0a4

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_theme/version.py
> Invenio-Theme v1.0.0a5

- invenio_theme/templates/invenio_theme/header.html
- invenio_theme/templates/invenio_theme/header_login.html
- tests/test_invenio_theme.py
* Adds next parameter to login link, so users are redirected back to
the page they came from.
* Adds extra template block in nav bar.
> templates: login button next redirect

- invenio_theme/version.py
> version: post-release bump

- invenio_theme/templates/invenio_theme/footer.html
* Adds links to the template (inside the footer section) to set the
language of the session.
Co-Authored-By: Jiri Kuncar <jiri.kuncar@cern.ch>
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>
> templates: addition of language selector

- invenio_theme/templates/invenio_theme/page_settings.html
> templates: template block fixes

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_theme/version.py
> release: v1.0.0a8

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_theme/version.py
Signed-off-by: Esteban J. G. Gabancho <esteban.gabancho@gmail.com>
> release: v1.0.0a9

- invenio_theme/ext.py
- invenio_theme/templates/invenio_theme/page_settings.html
* Fixes issue with computing active menu itme text.
> ext: breadcrumb init + settings title fix

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_theme/version.py
> release: v1.0.0a10

- invenio_theme/templates/invenio_theme/500.html
> templates: sentry error identifier support

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_theme/version.py
> release: v1.0.0a11

- invenio_theme/templates/invenio_theme/page.html
- tests/conftest.py
* Fixes text direction detection in base template.  (closes #44)
> templates: text direction based on locale

- examples/app.py
- invenio_theme/__init__.py
- invenio_theme/bundles.py
- run-tests.sh
- setup.py
- tests/test_invenio_theme.py
closes inveniosoftware/invenio-assets#41
> installation: support for webassets>=0.12

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_theme/version.py
> release: v1.0.0a14

- .gitignore
- invenio_theme/bundles.py
- invenio_theme/ext.py
- invenio_theme/static/js/base.js
- invenio_theme/static/js/invenio_theme/admin.js
- invenio_theme/static/scss/invenio_theme/admin.scss
- invenio_theme/templates/invenio_theme/admin.html
- invenio_theme/templates/invenio_theme/admin_header.html
- invenio_theme/templates/invenio_theme/admin_layout.html
- invenio_theme/templates/invenio_theme/footer.html
- setup.py
* Extension on @jirikuncar's branch to improve admin display.
> admin: admin-lte display improvements

- invenio_theme/bundles.py
- tests/test_invenio_theme.py
> bundles: configurable skin

- MANIFEST.in
- examples/app-setup.sh
- examples/app-teardown.sh
- examples/app.py
- tests/test_examples_app.py
* Adds test_examples_app.py. (closes #65)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
> tests: addition of test_examples_app.py

- MAINTAINERS
> docs: new maintainer 

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_theme/version.py
> release: v1.0.0a15

- invenio_theme/bundles.py
- invenio_theme/static/scss/invenio_theme/admin.scss
- invenio_theme/templates/invenio_theme/admin.html
Signed-off-by: Alexander Ioannidis <a.ioannidis@cern.ch>
> views: style fixes for AdminLTE

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_theme/version.py
> release: v1.0.0a16

- invenio_theme/bundles.py
- invenio_theme/templates/invenio_theme/admin.html
* Adds missing Moment.js library and block tail in admin template.
(closes inveniosoftware/invenio-admin#42)
> bundles: addition of Moment.js

- examples/app-setup.sh
- examples/app-teardown.sh
- invenio_theme/bundles.py
- setup.py
* Fixes issue with build failures due to clean-css v4 and fixes in
Invenio-I18N.
> global: build failure fix

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_theme/version.py
- setup.py
> relelase: v1.0.0a17

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_theme/version.py
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
> release: v1.0.0b1

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_theme/version.py
> release: v1.0.0b2

- invenio_theme/__init__.py
* Adds documentation about the front page. (closes #96)
> docs: addition of front page documentation

- invenio_theme/assets/js/invenio_theme/base.js
* Imports jQuery from Webpack.
Signed-off-by: Nikos Filippakis <nikolaos.filippakis@cern.ch>
> theme: import jQuery

- docs/examplesapp.rst
- examples/app.py
* fix example app rendering problems on readthedocs. (closes #104)
Signed-off-by: Harri Hirvonsalo <harri.hirvonsalo@cern.ch>
> docs: fix example app rendering problems on readthedocs

- invenio_theme/templates/invenio_theme/footer.html
Addresses inveniosoftware/invenio-app-ils#21
> templates: remove inline CSS

- invenio_theme/static/scss/invenio_theme/styles.scss
- invenio_theme/templates/invenio_theme/javascript.html
- invenio_theme/templates/invenio_theme/page.html
Signed-off-by: Diego Rodriguez <diego.rodriguez@cern.ch>
> templates: prevent Angular to execute inline CSS

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_theme/version.py
- setup.py
> release: v1.0.0b3

- CHANGES.rst
- RELEASE-NOTES.rst
- invenio_theme/version.py
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
> release: v1.0.0b4

- invenio_theme/webpack.py
Addresses https://github.com/inveniosoftware/cookiecutter-invenio-instance/issues/100
Signed-off-by: Dinos Kousidis <dinos.kousidis@cern.ch>
> webpack: upgrade moment version

- CHANGES.rst
- invenio_theme/version.py
* Closes #135 
Signed-off-by: Jan Okraska <jan.okraska@cern.ch>
> release: v1.1.4

- .travis.yml
- CHANGES.rst
- examples/app.py
- invenio_theme/version.py
- requirements-devel.txt
- setup.py
- tests/conftest.py
> Centralize Flask deps and release v1.2.0

- invenio_theme/templates/semantic-ui/invenio_theme/footer.html
closes inveniosoftware/invenio-i18n#84
> template: switch columns and right align lang picker

- MANIFEST.in
- invenio_theme/assets/semantic-ui/less/invenio_theme/site/collections/menu.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/site/collections/menu.variables
- invenio_theme/assets/semantic-ui/less/invenio_theme/site/elements/container.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/site/elements/container.variables
- invenio_theme/assets/semantic-ui/less/invenio_theme/site/elements/input.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/site/globals/site.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/site/globals/site.variables
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme.config
- invenio_theme/templates/semantic-ui/invenio_theme/body.html
- invenio_theme/templates/semantic-ui/invenio_theme/breadcrumbs.html
- invenio_theme/templates/semantic-ui/invenio_theme/footer.html
- invenio_theme/templates/semantic-ui/invenio_theme/frontpage.html
- invenio_theme/templates/semantic-ui/invenio_theme/header.html
- invenio_theme/templates/semantic-ui/invenio_theme/header_frontpage.html
- invenio_theme/templates/semantic-ui/invenio_theme/header_login.html
- invenio_theme/templates/semantic-ui/invenio_theme/page_cover.html
- invenio_theme/templates/semantic-ui/invenio_theme/page_error.html
* created overwrites of semantic-ui
* fixed css classes in templates
* closes #156
> Semantic styles

- invenio_theme/assets/semantic-ui/js/invenio_theme/theme.js
- invenio_theme/templates/semantic-ui/invenio_theme/header_login.html
> header-login: open dropdown on click

- invenio_theme/templates/semantic-ui/invenio_theme/header_login.html
> header_login: fixes button color in Safari

- CHANGES.rst
- invenio_theme/templates/semantic-ui/invenio_theme/header_login.html
- invenio_theme/version.py
> Fix login header buttons height

- invenio_theme/templates/semantic-ui/invenio_theme/header_login.html
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/184
> header_login: fix menu links

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/elements/header.overrides
closes https://github.com/inveniosoftware/invenio-theme/issues/166. 
Depends on https://github.com/inveniosoftware/invenio-accounts/pull/334
> Set reset header

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/elements/header.overrides
closes inveniosoftware/invenio-theme#164
depends on https://github.com/inveniosoftware/invenio-accounts/pull/335
> login: fix login form height

- invenio_theme/assets/semantic-ui/js/invenio_theme/theme.js
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/collections/message.overrides
- invenio_theme/templates/semantic-ui/invenio_theme/header_login.html
- invenio_theme/templates/semantic-ui/invenio_theme/macros/messages.html
* Adds a close icon
* Shorter height for the message
> messages: fix styling  in flashed messages

- CHANGES.rst
- invenio_theme/version.py
> release: v1.3.0a9

- invenio_theme/config.py
- invenio_theme/templates/invenio_theme/admin_header.html
- invenio_theme/templates/invenio_theme/header_frontpage.html
- invenio_theme/templates/semantic-ui/invenio_theme/admin_header.html
- invenio_theme/templates/semantic-ui/invenio_theme/header_frontpage.html
- invenio_theme/translations/tr/LC_MESSAGES/messages.po
* marked strings for translation
* added translations for Turkish language
> marked strings for translation, added translations for Turkish language

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/collections/message.overrides
- invenio_theme/templates/semantic-ui/invenio_theme/macros/messages.html
Issue: https://github.com/inveniosoftware/invenio-app-rdm/issues/237
> flashMessages: Fixes alignment

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/collections/menu.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.overrides
- invenio_theme/templates/semantic-ui/invenio_theme/header.html
> styles: Aligns header

- CHANGES.rst
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.overrides
- invenio_theme/version.py
* Needed for https://github.com/inveniosoftware/invenio-accounts/pull/343
* closes: inveniosoftware/invenio-app-rdm#255
> style: Adds new rule for login

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/elements/segment.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.overrides
- invenio_theme/templates/semantic-ui/invenio_theme/page_settings.html
> semantic: Harmonize headers

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.overrides
- invenio_theme/templates/semantic-ui/invenio_theme/page_cover.html
partially adresses https://github.com/inveniosoftware/invenio-app-rdm/issues/259 and https://github.com/inveniosoftware/invenio-app-rdm/issues/170
Also fixes fixes this [comment](https://github.com/inveniosoftware/invenio-accounts/pull/351#pullrequestreview-541069606) (center the logo)
> styles: Adds responsive login/sign up pages

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/collections/message.overrides
Closes inveniosoftware/invenio-formatter#72
> semantic: override message for doi badges

- MANIFEST.in
- invenio_theme/assets/semantic-ui/js/invenio_theme/theme.js
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/elements/container.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/navbar/navbar.less
- invenio_theme/templates/semantic-ui/invenio_theme/header.html
* Needed for https://github.com/inveniosoftware/invenio-app-rdm/pull/427
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/259
> styles: Adds responsive navbar

- invenio_theme/assets/semantic-ui/js/invenio_theme/admin.js
- invenio_theme/webpack.py
> webpack: fix theme-admin.css not found

- CHANGES.rst
- invenio_theme/assets/semantic-ui/js/invenio_theme/theme.js
- invenio_theme/version.py
closes https://github.com/inveniosoftware/invenio-oauth2server/issues/222
> semantic-ui: fix dropdown query

- invenio_theme/assets/semantic-ui/js/invenio_theme/theme.js
> semanticUI: Fix user profile dropdown

- CHANGES.rst
- invenio_theme/assets/semantic-ui/js/invenio_theme/theme.js
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.overrides
- invenio_theme/version.py
* closes https://github.com/inveniosoftware/invenio-previewer/issues/139
> Fixe semantic accordion

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/elements/container.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/elements/segment.overrides
- invenio_theme/templates/semantic-ui/invenio_theme/breadcrumbs.html
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/510
> breadcrumbs: fix styling issues

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/collections/grid.overrides
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/515
> theme: add deposit grid classes

- .gitignore
- invenio_theme/translations/de/LC_MESSAGES/messages.po
- invenio_theme/translations/messages.pot
- setup.cfg
> babel: set use fuzzy true

- invenio_theme/assets/semantic-ui/js/invenio_theme/theme.js
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/collections/message.overrides
- invenio_theme/templates/semantic-ui/invenio_theme/macros/messages.html
addresses [#1192](https://github.com/inveniosoftware/invenio-app-rdm/issues/1192)
- Wrapped icon in button & adjusted columns for alignment.
- Added closing logic for keyboard.
> flash message: make accessible by keyboard

- invenio_theme/assets/semantic-ui/js/invenio_theme/theme.js
- invenio_theme/assets/semantic-ui/js/invenio_theme/truncate.js
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.overrides
- invenio_theme/templates/invenio_theme/macros/truncate.html
- invenio_theme/webpack.py
Add a truncate text jinja macro with show all/less buttons.
closes: https://github.com/inveniosoftware/invenio-communities/issues/401
closes: https://github.com/inveniosoftware/invenio-app-rdm/issues/1280
> Common: add css rule to truncate up to two lines of content

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/collections/message.overrides
- invenio_theme/templates/semantic-ui/invenio_theme/macros/messages.html
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1427
> flash message: fix styling

- invenio_theme/templates/semantic-ui/invenio_theme/page_settings.html
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1383
> account page: add h1

- babel.ini
- invenio_theme/translations/messages.pot
* remove jinja extensions
* update .pot
related inveniosoftware/invenio-app-rdm#1664
> i18n: extract messages

- invenio_theme/translations/de/LC_MESSAGES/messages.po
* add german translations
related inveniosoftware/invenio-app-rdm/issues/1664
> i18n: adds german translation

- invenio_theme/assets/semantic-ui/js/invenio_theme/theme.js
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1616 
- Adds `imagePlaceholder` function to all images with `.has-placeholder`
> theme: add image placeholder function to has-placeholder class

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/modules/search.overrides
Make search icon a functional button.
closes: inveniosoftware/invenio-search-ui#152
> Header Searchbar: allow empty search

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/collections/menu.overrides
closes https://github.com/inveniosoftware/invenio-administration/issues/2
> back office: add styling for top nav

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/collections/grid.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/collections/grid.variables
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/collections/menu.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/elements/image.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.variables
Closes https://github.com/inveniosoftware/invenio-administration/issues/14
Related to PR https://github.com/inveniosoftware/invenio-administration/pull/16 <<-- Screenshots available
- Adds styling for sidebar menus and top navigation
> add styling for  invenio-administration (backoffice) sidebar

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/collections/form.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/collections/menu.overrides
- invenio_theme/config.py
> administration: add admin styling

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/collections/grid.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/collections/menu.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.variables
closes https://github.com/inveniosoftware/invenio-administration/issues/64
> administration: change sidenav color

- .github/workflows/i18n-pull.yml
- .github/workflows/i18n-push.yml
> ci: i18n pull&push cleanup

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.overrides
* closes: [inveniosoftware/invenio-administration#56](https://github.com/inveniosoftware/invenio-administration/issues/43)
> Facets: move facets to invenio-search-ui REQUIRES [invenio-search-ui#162]

- invenio_theme/templates/semantic-ui/invenio_theme/header_login.html
* closes: inveniosoftware/invenio-administration#66
Admin:
Not admin:
> Administration: add admin link in the profile menu

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.overrides
closes: https://github.com/inveniosoftware/invenio-administration/issues/61
> Margins and paddings: Add new auto generation options

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.variables
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1890
Sets global font to Helvetica
> global: set font to Helvetica

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/elements/container.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.overrides
* closes https://github.com/inveniosoftware/invenio-administration/issues/52
> site: adds center text align rule

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.overrides
Closes https://github.com/inveniosoftware/invenio-administration/issues/109
> global: add word-break-all class

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/modules/dropdown.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/views/item.overrides
Move action buttons to a dropdown.
closes: inveniosoftware/invenio-requests#264
> Requests mobile: center content

- invenio_theme/assets/semantic-ui/js/invenio_theme/Media.js
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/modules/dropdown.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/views/item.overrides
* closes: inveniosoftware/invenio-requests#264
> RequestsActions: fix merging issues

- invenio_theme/assets/semantic-ui/js/invenio_theme/theme.js
Closes https://github.com/inveniosoftware/invenio-theme/issues/301
- Checks if image loaded correctly, and if not, adds placeholder image
> theme: add placeholder image function

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.overrides
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/9
> Truncate lines: expand options

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.overrides
Closes https://github.com/inveniosoftware/demo-inveniordm/issues/122
Moves `auto-column-grid` class from `invenio-app-rdm` (See discussion https://github.com/inveniosoftware/invenio-app-rdm/pull/2026)
> theme: add auto-column-grid class

- CHANGES.rst
- invenio_theme/__init__.py
> release: v1.4.8

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/elements/button.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.overrides
Align top first column content of the details view
Display sorting options next to the search bar
closes: inveniosoftware/invenio-pages#66
> Administration: allow pre-formatted input in details view

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.overrides
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2075
> site: add global utility classes

- CHANGES.rst
- invenio_theme/__init__.py
> release: v2.2.0

- invenio_theme/assets/semantic-ui/js/invenio_theme/theme.js
- invenio_theme/templates/semantic-ui/invenio_theme/page_settings.html
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2301
> settings page: Improve template for a11y

- CHANGES.rst
- invenio_theme/__init__.py
> release: v2.3.0

- CHANGES.rst
- invenio_theme/__init__.py
> release: v2.4.0

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/collections/message.overrides
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2315
Solves the following issue:
> message: reduce z-index to prevent unwanted overlap

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.overrides
* closes https://github.com/zenodo/who-rdm/issues/80
> global: add font for code

- CHANGES.rst
- invenio_theme/__init__.py
> release: v2.5.4

- CHANGES.rst
- invenio_theme/__init__.py
> release: v2.5.5

- invenio_theme/assets/semantic-ui/js/invenio_theme/theme.js
* closes https://github.com/zenodo/rdm-project/issues/433
> community logo: fix rendering a placeholder

- CHANGES.rst
- invenio_theme/__init__.py
> release: v2.5.7

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.variables
Partially fixes [#421](https://github.com/zenodo/rdm-project/issues/421)
**Reminder**
2. You agree that …
> editor: added css for editor rendered output

- invenio_theme/assets/bootstrap3/scss/invenio_theme/cover.scss
- invenio_theme/assets/bootstrap3/scss/invenio_theme/header.scss
- invenio_theme/assets/bootstrap3/scss/invenio_theme/styles.scss
- invenio_theme/assets/semantic-ui/scss/invenio_theme/header.scss
- invenio_theme/assets/semantic-ui/scss/invenio_theme/styles.scss
* webpack: add tinymce to assets
* closes https://github.com/inveniosoftware/invenio-app-ils/issues/1188
> global: change math operation to compatible with sass2.0

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.overrides
Closes [2635](https://github.com/inveniosoftware/invenio-app-rdm/issues/2635)
Closes [2643](https://github.com/inveniosoftware/invenio-app-rdm/pull/2643)
**Reminder**
1. You license your …
> CSS: Fix overflow for description in record details

- invenio_theme/config.py
- invenio_theme/ext.py
- invenio_theme/templates/invenio_theme/page.html
- invenio_theme/templates/invenio_theme/page_admin.html
- invenio_theme/templates/semantic-ui/invenio_theme/page.html
- invenio_theme/templates/semantic-ui/invenio_theme/page_admin.html
- tests/test_invenio_theme.py
- See inveniosoftware/invenio-app-rdm#2689
> global: add meta generator tag

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/collections/menu.overrides
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/80
> header:  increase invenio menu z-index

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.overrides
Updated the styling of the border from dashed to solid. See below:
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder**
2. You agree that you have …
> css: updated table border style

- invenio_theme/assets/semantic-ui/js/invenio_theme/theme.js
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/198
> global: add an empty global plugin

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/elements/header.overrides
> Please describe briefly your pull request.
https://github.com/inveniosoftware/invenio-accounts/pull/495 removes [all uses of this class](https://github.com/search?q=%28org%3Ainveniosoftware+OR+org%3Azenodo%29+reset-password&type=code)
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contri …
> chore: remove unused rule

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.overrides
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/193
> site: add font-weight normal

- .github/workflows/pypi-publish.yml
- CHANGES.rst
- invenio_theme/__init__.py
- setup.cfg
- setup: pin dependencies
- setup: change to reusable workflows
- release: v3.5.1
> pin dependencies

- CHANGES.rst
- invenio_theme/__init__.py
- setup.cfg
- setup: bump major dependencies
- release: v4.0.0
> bump major

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/collections/grid.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/elements/segment.overrides
* closes https://github.com/inveniosoftware/invenio-jobs/issues/67
> overrides: add table and grid log values
