inveniosoftware/invenio-theme

- invenio_theme/templates/invenio_theme/macros/messages.html
* Fixes issue with message flashing not displaying the actual message.
* Sets default category to 'info'.
> templates: message flash fix

- invenio_theme/static/js/settings.js
* FIX Removes last semicolon from `settings.js` because raised
SyntaxError while building the assets.
---
```bash
$ cds assets build
Building bundle: gen/packed.%(version)s.js
Failed, error was: requirejs: subprocess returned a non-success result code: 1, stdout=Error: Error: Build file /Users/drjova/.virtualenvs/invenio3/lib/python2.7/site-packages/invenio_theme/static/js/settings.js is malformed: SyntaxError: Unexpected token ;
at Function.build.createConfig (/usr/local/lib/node_modules/requirejs/bin/r.js:26850:23)
```
> static: fix settings.js syntax error

- invenio_theme/ext.py
- invenio_theme/templates/invenio_theme/breadcrumbs.html
- invenio_theme/templates/invenio_theme/header.html
- invenio_theme/templates/invenio_theme/page.html
- tests/test_invenio_theme.py
* Adds search bar in header. (closes #35)
* Adds template blocks to page and header templates for better
customization.
> templates: search bar in header

- docs/conf.py
- invenio_theme/templates/invenio_theme/page_cover.html
* FIX Fixes issue when `THEME_LOGO` was set to `None` (closes #48).
> templates: allow no logo

- RELEASE-NOTES.rst
- invenio_theme/translations/da/LC_MESSAGES/messages.po
- setup.cfg
- setup.py
* Changes `invenio-software.org` to `inveniosoftware.org` to use the
same dashless canonical ID everywhere (GitHub, Twitter, Web).
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
> global: inveniosoftware.org

- invenio_theme/templates/invenio_theme/page.html
- tests/conftest.py
- tests/test_invenio_theme.py
* Uses `i18n.locale.language` instead of `g.ln` for `<html lang="...">`.
(closes #73)
> templates: fix of html lang attribute

- invenio_theme/templates/invenio_theme/admin_layout.html
* Adds alphabetical sorting of menu to prevent menu items from jumping
around based on the current loading order.
> templates: admin menu sorting

- invenio_theme/templates/invenio_theme/footer.html
* Fixes issue with "Powered by Invenio" not being visible due to the
column being pull off the screen for single language sites.
> templates: invisible powered by text fix

- invenio_theme/config.py
- invenio_theme/ext.py
- invenio_theme/static/scss/invenio_theme/body.scss
- invenio_theme/static/scss/invenio_theme/cover.scss
- invenio_theme/static/scss/invenio_theme/header.scss
- invenio_theme/static/scss/invenio_theme/variables.scss
- invenio_theme/templates/invenio_theme/frontpage.html
- invenio_theme/templates/invenio_theme/header_frontpage.html
- invenio_theme/templates/invenio_theme/page_cover.html
- invenio_theme/views.py
- tests/conftest.py
- tests/helpers.py
- tests/test_invenio_theme.py
* Fixes issues with ADMIN_BASE_TEMPLATE not being set.
* Adds new front-page template and front-page view (optional) to render
a basic front-page. (closes #90)
* Changes theme colors from gray to inveniosoftware.org default.
> global: frontpage and theme updates

- docs/conf.py
- invenio_theme/bundles.py
- pytest.ini
- run-tests.sh
* Removes unnecessary output parameter from js Bundle. (closes #89)
* doctests are now executed with pytest instead of sphinx. (closes #99)
> remove fixme and simplify tests

- tests/test_examples_app.py
* Removes `-h` flag on `flask run` following latest cookiecutter. (closes #105)
Signed-off-by: Diego Rodriguez <diego.rodriguez@cern.ch>
> tests: increase delay while app gets created

- invenio_theme/templates/semantic-ui/invenio_theme/header_login.html
Changes sign's up button icon from:
to
> header_login: change sign-up icon

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/elements/header.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/elements/segment.overrides
- invenio_theme/templates/semantic-ui/invenio_theme/breadcrumbs.html
- invenio_theme/templates/semantic-ui/invenio_theme/header.html
> breadcrumbs: style breadcrumbs in profile page

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/collections/menu.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/elements/header.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/elements/segment.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.overrides
- invenio_theme/templates/semantic-ui/invenio_theme/page_settings.html
* Aligns header
* Increments whitespaces between panels
* Menu highlight changed to blue
* Harmonize font-size of panel headers
* Selected breadcrumb cannot be
clicked anymore
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/235
> styles: Fix styling on settings page

- invenio_theme/templates/semantic-ui/invenio_theme/header_login.html
The length is truncated to 31 characters to fit 95% of the emails according to this article: https://www.freshaddress.com/blog/long-email-addresses/
EDIT
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/267
> ui: truncate long email addresses

- invenio_theme/config.py
Closes https://github.com/inveniosoftware/invenio-search-ui/issues/83
The `HEADER_TEMPLATE` variable needs to be defined somewhere to fix the issue. Why here? Because the default value is `invenio_theme/header.html`. 
The issue raises from `invenio-search-ui`, which only defines it in tests (see [here](https://github.com/inveniosoftware/invenio-search-ui/blob/7556f8f6a97fb9831664d02b061c9ea6b7068936/tests/conftest.py#L43)). The referenced template is a mere mock one, so it cannot be referenced in the `config.py`. `invenio-search-ui` defines a `header.html` template, but it extends `HEADER_TEMPLATE` (setting this to the value would cause infinite recursion). Then it would set the default value [here](https://github.com/inveniosoftware/invenio-search-ui/blob/2fecd7a89dfd99235908c7a722ad6d31e …
> config: add base header variable

- invenio_theme/webpack.py
Closes https://github.com/inveniosoftware/invenio-theme/issues/200
Changed alias. Currently evaluating the implications:
- Cookiecutter Invenio Instance. Checked the code and there is no reference to the alias (did a grep also and nothing). Bootstrapped and instance and seems to be working. See ss below, it can be seen is OK and it also has semantic UI classes.
- Cookiecutter Invenio RDM, same procedure as above
> webpack: change less alias to follow conventions

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/collections/menu.overrides
- invenio_theme/templates/semantic-ui/invenio_theme/header.html
- invenio_theme/templates/semantic-ui/invenio_theme/page_settings.html
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/512
Now menu is also controlled by `brand` class and can easily change if the `@brandColor` is set to a different color e.g `purple`. With that change the UI becomes
> Brand menu

- invenio_theme/templates/semantic-ui/invenio_theme/page.html
- invenio_theme/templates/semantic-ui/invenio_theme/page_error.html
- invenio_theme/templates/semantic-ui/invenio_theme/page_settings.html
- Added "main" landmarks to two templates (including an "id", which will be useful for "skip to content" links)
- Removed " ng-csp" from body tag
> A11y landmarks

- MANIFEST.in
if this is not present the `.mo` extension files will not be added to the package creation.
closes #260
> i18n: include translation files

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.variables
* bumping up contrast to "at least 4.5:1 for normal text"  (This gray on white is 4.6:1)
> Set and use semantic UI's @mutedTextColor variable

- invenio_theme/templates/semantic-ui/invenio_theme/macros/messages.html
- invenio_theme/templates/semantic-ui/invenio_theme/page_cover.html
Closes [#143](https://github.com/inveniosoftware/invenio-app-rdm/issues/143)
- Changed grid layout to span full width and adjusted the col-widths for the flash message if centered
- Changed the layout for the page_cover-template to use the default semantic-ui columns instead of `.column.centered` overwritten in `site.overrides` with `width: 33% !important;` + media queries. ([`/invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.overrides`](https://github.com/inveniosoftware/invenio-theme/blob/master/invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.overrides#L25)). This to make sure the text aligns with the segment below.
__Note:__ The script that enables dismissing the message is added in …
> cover page: make flash message span full width

- invenio_theme/assets/semantic-ui/js/invenio_theme/theme.js
- invenio_theme/templates/semantic-ui/invenio_theme/macros/messages.html
- invenio_theme/templates/semantic-ui/invenio_theme/page_cover.html
- Add `role="alert"` and `display:none;` to message-wrapper. 
- Replace `display:none;` with `display:block;` on page load to trigger the announcement by the screen reader.
Closes [#1191](https://github.com/inveniosoftware/invenio-app-rdm/issues/1191)
> messages: announce alert message to screen readers

- invenio_theme/templates/semantic-ui/invenio_theme/page_settings.html
- Previously, the number of opening and closing tags was not the same in `page_settings.html`. This caused problems in child templates, as several tags were closed prematurely.
- Fixed indentation and jinja blocks' spacing for better readability, which might have led to the problem mentioned above. 
Ping: @kpsherva
> Fix tag mismatch in page_settings template & refactor blocks

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.overrides
- invenio_theme/templates/semantic-ui/invenio_theme/page.html
* Adds new block to all pages for a bypass link
* Adds CSS to hide the block except when it's focused
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1171
> Bypass links: allow keyboard-only users to skip navigation

- invenio_theme/assets/semantic-ui/js/invenio_theme/theme.js
Closes https://github.com/inveniosoftware/invenio-theme/issues/286
Adds global accordion init function with accessibility features. Requires all accordions to have a `trigger`-class on the element that will open/close the accordion. 
Tested with VoiceOver on Mac.
> theme: add accessibility to ui-accordions

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/collections/grid.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/collections/grid.variables
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/elements/button.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/elements/button.variables
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/elements/header.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/elements/header.variables
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/elements/icon.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/elements/icon.variables
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/elements/label.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/elements/label.variables
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/elements/segment.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.variables
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/modules/progress.overrides
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1503
Adds general class names for colors where colors were hard coded.
The new class names used are:
- `.warning` (rdm yellow)
- `.positive` (rdm green)
- `.negative` (rdm red)
- `.expired` (rdm orange)
- `.neutral` (rdm grey)
The following mentioned PRs are needed (see timeline).
> overrides: add general color classes and variables

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.overrides
Closes https://github.com/zenodo/who-rdm/issues/23
When the `.inline` class was moved from `invenio-app-rdm` to `invenio-theme`, it also became `!important` which it was not before. This is causing an override of the SUI classes for `.inline.fields`, which is the reason for this change.
See:
`invenio-theme`, where the class became important:
- https://github.com/inveniosoftware/invenio-theme/commit/7bf5d135bd681196e2c3421f33098100ee8ac065
History of `invenio-app-rdm` where it is not important:
- https://github.com/inveniosoftware/invenio-app-rdm/blob/eb2b383c646045fc7420601d78311a7424a98432/invenio_app_rdm/theme/assets/semantic-ui/less/invenio_app_rdm/theme/globals/site.overrides#L456
> site overrides: remove important from inline class

- CHANGES.rst
- docs/conf.py
- invenio_theme/__init__.py
- invenio_theme/config.py
- invenio_theme/ext.py
- invenio_theme/views.py
- invenio_theme/webpack.py
- run-tests.sh
- setup.cfg
- tests/conftest.py
- tests/helpers.py
- tests/test_invenio_theme.py
- tests/test_invenio_theme_error_handler.py
- fix: --dry-run ignored
- fix: filter pytest deprecation warnings
- global: remove python2.7 support
- global: use invenio-i18n as flask-babel proxy
- NOTE: to make this testable it is necessary to release invenio-i18n
> migrate to flask babel

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.overrides
Closes https://github.com/zenodo/rdm-project/issues/171
Adds `.no-wrap` to `.auto-column-grid`, to be able to prevent unwanted wrapping on tablet & mobile screens. Used in `<CommunityCompactItem />` PR: https://github.com/inveniosoftware/invenio-communities/pull/995
> theme: Add responsive settings for auto-column-grid

- CHANGES.rst
- invenio_theme/__init__.py
- setup.cfg
- installation: pin Flask-Menu to <1.0.0
- release: v2.5.2
> Pin Flask-Menu and release v2.5.2

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/globals/site.overrides
> styling: add 3 column template class

- CHANGES.rst
- docs/conf.py
- invenio_theme/__init__.py
- invenio_theme/config.py
- invenio_theme/ext.py
- invenio_theme/icons.py
- invenio_theme/proxies.py
- invenio_theme/shared.py
- invenio_theme/templates/invenio_theme/admin_header.html
- invenio_theme/templates/invenio_theme/header.html
- invenio_theme/templates/invenio_theme/header_login.html
- invenio_theme/templates/invenio_theme/page_settings.html
- invenio_theme/templates/semantic-ui/invenio_theme/admin_header.html
- invenio_theme/templates/semantic-ui/invenio_theme/header.html
- invenio_theme/templates/semantic-ui/invenio_theme/header_login.html
- invenio_theme/templates/semantic-ui/invenio_theme/page_settings.html
- invenio_theme/views.py
- setup.cfg
- tests/conftest.py
- tests/test_invenio_theme.py
- introduce shared menu outside of application context
- global: refactor current_theme_icons
NOTE: it works without flask-menu and invenio-base release, BUT it works also if those are released first with flask>=3.0.0
> add init function

- invenio_theme/templates/semantic-ui/invenio_theme/401.html
- invenio_theme/templates/semantic-ui/invenio_theme/403.html
- invenio_theme/templates/semantic-ui/invenio_theme/404.html
- invenio_theme/templates/semantic-ui/invenio_theme/429.html
- invenio_theme/templates/semantic-ui/invenio_theme/500.html
- invenio_theme/templates/semantic-ui/invenio_theme/page_settings.html
> Please describe briefly your pull request.
Related to https://github.com/inveniosoftware/invenio-theme/pull/382 but not dependent.
Should I also change this in the other theme https://github.com/inveniosoftware/invenio-theme/blob/master/invenio_theme/templates/invenio_theme/404.html etc?
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of …
> bug: add missing <title>s

- invenio_theme/config.py
- invenio_theme/templates/invenio_theme/page.html
- invenio_theme/templates/semantic-ui/invenio_theme/page.html
* Closes https://github.com/zenodo/zenodo-rdm/issues/951.
* Generate robots meta tags from the `THEME_META_ROBOT_TAGS` config or
exlicitly set via the `meta_robot_tags` Jinja variable.
> templates: add meta robot tags

- invenio_theme/assets/semantic-ui/less/invenio_theme/navbar/navbar.less
> The behavior described and updated in this PR was identified in InvenioRDM v12 with invenio-theme version `3.3.0`
The navbar logo size does not adjust immediately when transitioning from the `computer` to `tablet` breakpoint (`1300px`). It changes only when the page width is below `1200px`. The GIF below demonstrates this behavior.
This PR fixes this behavior by updating the image media query, ensuring the logo size changes consistently at the appropriate breakpoint. The GIF below presents the result of the proposed modification.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/# …
> navbar: update logo size in non-desktop devices

- invenio_theme/config.py
- invenio_theme/templates/semantic-ui/invenio_theme/page.html
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/133
> config: add MathJax support

- .github/workflows/tests.yml
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/collections/grid.overrides
* closes inveniosoftware/invenio-app-rdm#2838
> feat: style packages versions in administration panel

- invenio_theme/templates/invenio_theme/page.html
- invenio_theme/templates/semantic-ui/invenio_theme/page.html
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/198
> config: pass invenio config to main body

- invenio_theme/templates/semantic-ui/invenio_theme/page_cover.html
fixes: https://github.com/CERNDocumentServer/cds-rdm/issues/190
> templates: page_cover: Add banner to login template

- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/collections/form.overrides
- invenio_theme/assets/semantic-ui/less/invenio_theme/theme/elements/input.overrides
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/163
> form: some UI fixed for the deposit form

- CHANGES.rst
- invenio_theme/assets/semantic-ui/scss/invenio_theme/admin.scss
* Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.
More info and automated migrator: https://sass-lang.com/d/import
> fix: ModuleWarning: Deprecation Warning

- invenio_theme/ext.py
- invenio_theme/views.py
- run-tests.sh
*new*
Moved the error handling registration out of finalize_app (and still out of blueprint) into app loading. Left alone registration of a new `invenio_base.api_apps` app in the end. Repos are adding THEME_FRONTPAGE to their conftest and I'd rather not introduce more wide-spanning changes than necessary. Just 1 commit, so ready for review + merge.
*old*
~~- Move error handling to `finalize_app`~~
~~- Create a different ext instance in order to load config in an API app~~
~~The second point solves the failing tests using `create_api` across repos, but could also be solved on a repo by repo basis and setting `"THEME_FRONTPAGE"` in each test's app_config.~~
> app: register error handling in finalize + config for api_apps
